name: Simplegodmode
version: '${project.version}'
main: com.guedosha.simplegodmode.Simplegodmode
api-version: 1.16
authors: [ Guedosha ]
description: A simple god mode plugin
website: https://www.guedosha.com
commands:
  god:
    description: Makes you invincible
    usage: /<command> (target)
    aliases: [godmode]
  reload:
    description: Reloads the plugin config